// Client-side lookup table for English → Chinese geo names.
// Applied segment-by-segment to GDELT location strings.
const GEO = {
  // ── Countries ──
  'United States': '美国',
  'United Kingdom': '英国',
  'Russia': '俄罗斯',
  'China': '中国',
  'France': '法国',
  'Germany': '德国',
  'Japan': '日本',
  'South Korea': '韩国',
  'North Korea': '朝鲜',
  'India': '印度',
  'Pakistan': '巴基斯坦',
  'Afghanistan': '阿富汗',
  'Iran': '伊朗',
  'Iraq': '伊拉克',
  'Syria': '叙利亚',
  'Lebanon': '黎巴嫩',
  'Israel': '以色列',
  'Palestine': '巴勒斯坦',
  'Saudi Arabia': '沙特阿拉伯',
  'Yemen': '也门',
  'Turkey': '土耳其',
  'Egypt': '埃及',
  'Libya': '利比亚',
  'Sudan': '苏丹',
  'South Sudan': '南苏丹',
  'Ethiopia': '埃塞俄比亚',
  'Somalia': '索马里',
  'Kenya': '肯尼亚',
  'Nigeria': '尼日利亚',
  'Ghana': '加纳',
  'South Africa': '南非',
  'Democratic Republic of the Congo': '刚果民主共和国',
  'Congo': '刚果',
  'Cameroon': '喀麦隆',
  'Mali': '马里',
  'Niger': '尼日尔',
  'Burkina Faso': '布基纳法索',
  'Ukraine': '乌克兰',
  'Poland': '波兰',
  'Romania': '罗马尼亚',
  'Hungary': '匈牙利',
  'Sweden': '瑞典',
  'Norway': '挪威',
  'Finland': '芬兰',
  'Denmark': '丹麦',
  'Netherlands': '荷兰',
  'Belgium': '比利时',
  'Spain': '西班牙',
  'Italy': '意大利',
  'Portugal': '葡萄牙',
  'Greece': '希腊',
  'Switzerland': '瑞士',
  'Austria': '奥地利',
  'Czech Republic': '捷克',
  'Czechia': '捷克',
  'Slovakia': '斯洛伐克',
  'Serbia': '塞尔维亚',
  'Croatia': '克罗地亚',
  'Bosnia': '波斯尼亚',
  'Bosnia and Herzegovina': '波斯尼亚和黑塞哥维那',
  'North Macedonia': '北马其顿',
  'Slovenia': '斯洛文尼亚',
  'Montenegro': '黑山',
  'Albania': '阿尔巴尼亚',
  'Latvia': '拉脱维亚',
  'Lithuania': '立陶宛',
  'Estonia': '爱沙尼亚',
  'Moldova': '摩尔多瓦',
  'Belarus': '白俄罗斯',
  'Luxembourg': '卢森堡',
  'Iceland': '冰岛',
  'Ireland': '爱尔兰',
  'Malta': '马耳他',
  'Cyprus': '塞浦路斯',
  'Georgia': '格鲁吉亚',
  'Armenia': '亚美尼亚',
  'Azerbaijan': '阿塞拜疆',
  'Kazakhstan': '哈萨克斯坦',
  'Uzbekistan': '乌兹别克斯坦',
  'Tajikistan': '塔吉克斯坦',
  'Turkmenistan': '土库曼斯坦',
  'Kyrgyzstan': '吉尔吉斯斯坦',
  'Mongolia': '蒙古',
  'Laos': '老挝',
  'Cambodia': '柬埔寨',
  'Brunei': '文莱',
  'Timor-Leste': '东帝汶',
  'Papua New Guinea': '巴布亚新几内亚',
  'Morocco': '摩洛哥',
  'Algeria': '阿尔及利亚',
  'Tunisia': '突尼斯',
  'Senegal': '塞内加尔',
  'Ivory Coast': "科特迪瓦",
  "Côte d'Ivoire": "科特迪瓦",
  'Tanzania': '坦桑尼亚',
  'Uganda': '乌干达',
  'Rwanda': '卢旺达',
  'Mozambique': '莫桑比克',
  'Zimbabwe': '津巴布韦',
  'Zambia': '赞比亚',
  'Angola': '安哥拉',
  'Namibia': '纳米比亚',
  'Botswana': '博茨瓦纳',
  'Eritrea': '厄立特里亚',
  'Djibouti': '吉布提',
  'Central African Republic': '中非共和国',
  'Chad': '乍得',
  'Mauritania': '毛里塔尼亚',
  'Gabon': '加蓬',
  'Equatorial Guinea': '赤道几内亚',
  'Comoros': '科摩罗',
  'Madagascar': '马达加斯加',
  'Seychelles': '塞舌尔',
  'Mauritius': '毛里求斯',
  'Jordan': '约旦',
  'Kuwait': '科威特',
  'Bahrain': '巴林',
  'Oman': '阿曼',
  'Qatar': '卡塔尔',
  'United Arab Emirates': '阿联酋',
  'Cyprus': '塞浦路斯',
  'Venezuela': '委内瑞拉',
  'Bolivia': '玻利维亚',
  'Ecuador': '厄瓜多尔',
  'Uruguay': '乌拉圭',
  'Paraguay': '巴拉圭',
  'Panama': '巴拿马',
  'Costa Rica': '哥斯达黎加',
  'Guatemala': '危地马拉',
  'Honduras': '洪都拉斯',
  'El Salvador': '萨尔瓦多',
  'Nicaragua': '尼加拉瓜',
  'Dominican Republic': '多米尼加共和国',
  'Jamaica': '牙买加',
  'Trinidad and Tobago': '特立尼达和多巴哥',
  // ── Additional cities ──
  'Riga': '里加',
  'Vilnius': '维尔纽斯',
  'Tallinn': '塔林',
  'Chisinau': '基希讷乌',
  'Minsk': '明斯克',
  'Ljubljana': '卢布尔雅那',
  'Zagreb': '萨格勒布',
  'Sarajevo': '萨拉热窝',
  'Tirana': '地拉那',
  'Skopje': '斯科普里',
  'Podgorica': '波德戈里察',
  'Pristina': '普里什蒂纳',
  'Reykjavik': '雷克雅未克',
  'Dublin': '都柏林',
  'Valletta': '瓦莱塔',
  'Nicosia': '尼科西亚',
  'Kuala Lumpur': '吉隆坡',
  'Hanoi': '河内',
  'Phnom Penh': '金边',
  'Vientiane': '万象',
  'Naypyidaw': '内比都',
  'Colombo': '科伦坡',
  'Ulaanbaatar': '乌兰巴托',
  'Rabat': '拉巴特',
  'Tunis': '突尼斯市',
  'Accra': '阿克拉',
  'Dakar': '达喀尔',
  'Kampala': '坎帕拉',
  'Dar es Salaam': '达累斯萨拉姆',
  'Maputo': '马普托',
  'Luanda': '罗安达',
  'Harare': '哈拉雷',
  'Lusaka': '卢萨卡',
  'Windhoek': '温得和克',
  'Gaborone': '哈博罗内',
  'Muscat': '马斯喀特',
  'Manama': '麦纳麦',
  'Amman': '安曼',
  'Kuwait City': '科威特城',
  'Caracas': '加拉加斯',
  'Lima': '利马',
  'La Paz': '拉巴斯',
  'Quito': '基多',
  'Bogota': '波哥大',
  'Montevideo': '蒙得维的亚',
  'Asuncion': '亚松森',
  'Panama City': '巴拿马城',
  'Guatemala City': '危地马拉城',
  'San Jose': '圣何塞',
  'Tegucigalpa': '特古西加尔巴',
  'Managua': '马那瓜',
  'Santo Domingo': '圣多明各',
  'Myanmar': '缅甸',
  'Thailand': '泰国',
  'Vietnam': '越南',
  'Philippines': '菲律宾',
  'Indonesia': '印度尼西亚',
  'Malaysia': '马来西亚',
  'Singapore': '新加坡',
  'Bangladesh': '孟加拉国',
  'Sri Lanka': '斯里兰卡',
  'Nepal': '尼泊尔',
  'Australia': '澳大利亚',
  'New Zealand': '新西兰',
  'Canada': '加拿大',
  'Mexico': '墨西哥',
  'Brazil': '巴西',
  'Argentina': '阿根廷',
  'Colombia': '哥伦比亚',
  'Venezuela': '委内瑞拉',
  'Peru': '秘鲁',
  'Chile': '智利',
  'Cuba': '古巴',
  'Haiti': '海地',
  // ── Special regions ──
  'Gaza Strip': '加沙地带',
  'West Bank': '约旦河西岸',
  'Taiwan': '台湾',
  'Hong Kong': '香港',
  'Crimea': '克里米亚',
  'Kosovo': '科索沃',
  // ── Major cities ──
  'Washington': '华盛顿',
  'New York': '纽约',
  'Los Angeles': '洛杉矶',
  'Chicago': '芝加哥',
  'Houston': '休斯顿',
  'Miami': '迈阿密',
  'Atlanta': '亚特兰大',
  'Boston': '波士顿',
  'Philadelphia': '费城',
  'Seattle': '西雅图',
  'San Francisco': '旧金山',
  'Denver': '丹佛',
  'Dallas': '达拉斯',
  'Phoenix': '凤凰城',
  'Las Vegas': '拉斯维加斯',
  'London': '伦敦',
  'Paris': '巴黎',
  'Berlin': '柏林',
  'Madrid': '马德里',
  'Rome': '罗马',
  'Amsterdam': '阿姆斯特丹',
  'Brussels': '布鲁塞尔',
  'Vienna': '维也纳',
  'Warsaw': '华沙',
  'Prague': '布拉格',
  'Stockholm': '斯德哥尔摩',
  'Oslo': '奥斯陆',
  'Copenhagen': '哥本哈根',
  'Helsinki': '赫尔辛基',
  'Athens': '雅典',
  'Lisbon': '里斯本',
  'Budapest': '布达佩斯',
  'Bucharest': '布加勒斯特',
  'Kyiv': '基辅',
  'Kiev': '基辅',
  'Moscow': '莫斯科',
  'St. Petersburg': '圣彼得堡',
  'Istanbul': '伊斯坦布尔',
  'Ankara': '安卡拉',
  'Tehran': '德黑兰',
  'Baghdad': '巴格达',
  'Riyadh': '利雅得',
  'Dubai': '迪拜',
  'Abu Dhabi': '阿布扎比',
  'Doha': '多哈',
  'Kuwait City': '科威特城',
  'Beirut': '贝鲁特',
  'Damascus': '大马士革',
  'Amman': '安曼',
  'Jerusalem': '耶路撒冷',
  'Tel Aviv': '特拉维夫',
  'Gaza': '加沙',
  'Cairo': '开罗',
  'Tripoli': '的黎波里',
  'Tunis': '突尼斯',
  'Algiers': '阿尔及尔',
  'Casablanca': '卡萨布兰卡',
  'Nairobi': '内罗毕',
  'Addis Ababa': '亚的斯亚贝巴',
  'Lagos': '拉各斯',
  'Abuja': '阿布贾',
  'Accra': '阿克拉',
  'Johannesburg': '约翰内斯堡',
  'Cape Town': '开普敦',
  'Pretoria': '比勒陀利亚',
  'Kinshasa': '金沙萨',
  'Khartoum': '喀土穆',
  'Mogadishu': '摩加迪沙',
  'Kabul': '喀布尔',
  'Islamabad': '伊斯兰堡',
  'Karachi': '卡拉奇',
  'Lahore': '拉合尔',
  'New Delhi': '新德里',
  'Delhi': '德里',
  'Mumbai': '孟买',
  'Kolkata': '加尔各答',
  'Chennai': '金奈',
  'Dhaka': '达卡',
  'Kathmandu': '加德满都',
  'Colombo': '科伦坡',
  'Beijing': '北京',
  'Shanghai': '上海',
  'Guangzhou': '广州',
  'Shenzhen': '深圳',
  'Tokyo': '东京',
  'Osaka': '大阪',
  'Seoul': '首尔',
  'Pyongyang': '平壤',
  'Taipei': '台北',
  'Bangkok': '曼谷',
  'Hanoi': '河内',
  'Ho Chi Minh City': '胡志明市',
  'Manila': '马尼拉',
  'Jakarta': '雅加达',
  'Kuala Lumpur': '吉隆坡',
  'Singapore': '新加坡',
  'Yangon': '仰光',
  'Naypyidaw': '内比都',
  'Sydney': '悉尼',
  'Melbourne': '墨尔本',
  'Auckland': '奥克兰',
  'Toronto': '多伦多',
  'Ottawa': '渥太华',
  'Vancouver': '温哥华',
  'Montreal': '蒙特利尔',
  'Mexico City': '墨西哥城',
  'Havana': '哈瓦那',
  'Bogota': '波哥大',
  'Lima': '利马',
  'Santiago': '圣地亚哥',
  'Buenos Aires': '布宜诺斯艾利斯',
  'Sao Paulo': '圣保罗',
  'Rio de Janeiro': '里约热内卢',
  'Brasilia': '巴西利亚',
  'Baku': '巴库',
  'Yerevan': '埃里温',
  'Tbilisi': '第比利斯',
  'Minsk': '明斯克',
  'Chisinau': '基希讷乌',
  'Belgrade': '贝尔格莱德',
  'Zagreb': '萨格勒布',
  'Sarajevo': '萨拉热窝',
  'Tirana': '地拉那',
  'Pristina': '普里什蒂纳',
  'Skopje': '斯科普里',
  'Podgorica': '波德戈里察',
  'Nur-Sultan': '努尔苏丹',
  'Tashkent': '塔什干',
  'Dushanbe': '杜尚别',
  'Ashgabat': '阿什哈巴德',
  'Bishkek': '比什凯克',
  // ── US states ──
  'District of Columbia': '哥伦比亚特区',
  'California': '加利福尼亚',
  'Texas': '德克萨斯',
  'Florida': '佛罗里达',
  'New York': '纽约州',
  'Illinois': '伊利诺伊',
  'Pennsylvania': '宾夕法尼亚',
  'Ohio': '俄亥俄',
  'Georgia': '佐治亚',
  'North Carolina': '北卡罗来纳',
  'Michigan': '密歇根',
  'Virginia': '弗吉尼亚',
  'Washington': '华盛顿',
  'Arizona': '亚利桑那',
  'Massachusetts': '马萨诸塞',
  'Tennessee': '田纳西',
  'Indiana': '印第安纳',
  'Missouri': '密苏里',
  'Maryland': '马里兰',
  'Wisconsin': '威斯康星',
  'Colorado': '科罗拉多',
  'Minnesota': '明尼苏达',
  'South Carolina': '南卡罗来纳',
  'Alabama': '阿拉巴马',
  'Louisiana': '路易斯安那',
  'Kentucky': '肯塔基',
  'Oregon': '俄勒冈',
  'Oklahoma': '俄克拉荷马',
  'Connecticut': '康涅狄格',
  'Utah': '犹他',
  'Iowa': '爱荷华',
  'Nevada': '内华达',
  'Arkansas': '阿肯色',
  'Mississippi': '密西西比',
  'Kansas': '堪萨斯',
  'New Mexico': '新墨西哥',
  'Nebraska': '内布拉斯加',
  'West Virginia': '西弗吉尼亚',
  'Idaho': '爱达荷',
  'Hawaii': '夏威夷',
  'New Hampshire': '新罕布什尔',
  'Maine': '缅因',
  'Montana': '蒙大拿',
  'Rhode Island': '罗德岛',
  'Delaware': '特拉华',
  'South Dakota': '南达科他',
  'North Dakota': '北达科他',
  'Alaska': '阿拉斯加',
  'Vermont': '佛蒙特',
  'Wyoming': '怀俄明',
}

// Build a sorted list (longest first) for greedy matching.
const ENTRIES = Object.entries(GEO).sort((a, b) => b[0].length - a[0].length)

function translateSegment(seg) {
  const trimmed = seg.trim()
  // Strip trailing asterisks/stars (GDELT admin-level markers like "Baki*")
  const clean = trimmed.replace(/\*+$/, '').trim()
  // Try exact lookup (case-insensitive)
  const key = ENTRIES.find(([k]) => k.toLowerCase() === clean.toLowerCase())
  if (key) return key[1]
  return trimmed // keep original if not found
}

export function translateLocation(locStr) {
  if (!locStr) return locStr
  // Split on " · " first (multi-location separator), translate each location.
  return locStr
    .split(' · ')
    .map((loc) =>
      loc
        .split(', ')
        .map(translateSegment)
        .join(', ')
    )
    .join(' · ')
}
